<#
.SYNOPSIS
    Fails the build if any coverage report names a file git doesn't track.

.DESCRIPTION
    coverage.mintplayer.com resolves every path in a report by longest-suffix match against the
    `git ls-files` listing the upload action sends. A path that fails to match is **dropped
    silently** — the upload succeeds and the number is simply wrong. That is the same trap the C#
    repos defend against by pinning UseSourceLink/DeterministicReport to false, and the reason
    other MintPlayer repos rebase lcov paths before uploading.

    It matters more here than there, because our plugin lcov is generated by us rather than by a
    mature coverage tool. This converts the silent-drop class into a loud failure.

    Checks both lcov (`SF:`) and Cobertura (`<class filename="...">`) reports.

.PARAMETER Path
    Directory to scan for .lcov / .info / .xml reports.
#>
[CmdletBinding()]
param(
    [string]$Path = 'coverage'
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $Path)) {
    Write-Error "coverage directory not found: $Path"
    exit 2
}

$tracked = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($f in (& git ls-files)) { [void]$tracked.Add($f.Replace('\', '/')) }
if ($tracked.Count -eq 0) {
    Write-Error 'git ls-files returned nothing — not a git checkout?'
    exit 2
}

# The server matches by suffix, so accept a report path that is a suffix of a tracked path (or vice
# versa) rather than demanding an exact string match.
function Test-Resolvable([string]$reportPath) {
    $p = $reportPath.Replace('\', '/').TrimStart('./')
    if ($tracked.Contains($p)) { return $true }
    foreach ($t in $tracked) {
        if ($t.EndsWith("/$p", [System.StringComparison]::OrdinalIgnoreCase)) { return $true }
    }
    return $false
}

$checked = 0
$bad = @()

foreach ($report in (Get-ChildItem -Path $Path -Recurse -File -Include *.lcov, *.info, *.xml)) {
    foreach ($line in [System.IO.File]::ReadLines($report.FullName)) {
        $paths = @()
        if ($line -match '^\s*SF:(.+)$') { $paths += $Matches[1].Trim() }
        foreach ($m in [regex]::Matches($line, '<class[^>]*\bfilename="([^"]+)"')) { $paths += $m.Groups[1].Value }

        foreach ($p in $paths) {
            $checked++
            if (-not (Test-Resolvable $p)) { $bad += "$($report.Name): $p" }
        }
    }
}

if ($checked -eq 0) {
    Write-Error "no coverage report paths found under '$Path' — the reports are empty or missing"
    exit 2
}

if ($bad.Count -gt 0) {
    Write-Host "Coverage path tripwire FAILED — these paths would be silently dropped by the server:" -ForegroundColor Red
    $bad | Select-Object -Unique | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
    exit 1
}

Write-Host "Coverage path tripwire OK — $checked report path(s) resolve against git ls-files."
