<#
.SYNOPSIS
    Fails the build if any coverage report names a file git doesn't track.

.DESCRIPTION
    coverage.mintplayer.com resolves every path in a report by longest-suffix match against the
    `git ls-files` listing the upload action sends. A path that fails to match is **dropped
    silently** — the upload succeeds and the number is simply wrong. That is the same trap the C#
    repos defend against by pinning UseSourceLink/DeterministicReport to false, and the reason
    other MintPlayer repos rebase lcov paths before uploading.

    It matters more here than there, because our plugin lcov is generated by us rather than by a
    mature coverage tool. This converts the silent-drop class into a loud failure.

    Checks both lcov (`SF:`) and Cobertura (`<class filename="...">`) reports.

.PARAMETER Path
    Directory to scan for .lcov / .info / .xml reports.
#>
[CmdletBinding()]
param(
    [string]$Path = 'coverage'
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $Path)) {
    Write-Error "coverage directory not found: $Path"
    exit 2
}

$tracked = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($f in (& git ls-files)) { [void]$tracked.Add($f.Replace('\', '/')) }
if ($tracked.Count -eq 0) {
    Write-Error 'git ls-files returned nothing — not a git checkout?'
    exit 2
}

# Mirrors the ingest's PathNormalizer (MintPlayer.Spark/apps/CodeCoverage), which this used to describe
# but not implement. Two corrections, in OPPOSITE directions — the old version was both too strict and
# too permissive, so it rejected reports the server accepts AND passed ones it silently drops:
#
#   * BOTH directions match. The server tests `tracked.EndsWith(report) || report.EndsWith(tracked)`, so a
#     report path LONGER than the tracked one resolves. That is not exotic: coverlet's cobertura filename
#     is relative to the longest common prefix across all documents in the report, so one document outside
#     the repo pushes every path into the longer form.
#   * Exactly ONE candidate. The server requires a unique match; an ambiguous basename resolves to
#     nothing and the file is stored `Matched = false` — excluded from every number, with no error. That
#     is precisely the silent drop this tripwire exists to catch, and accepting the first hit missed it.
function Resolve-ReportPath([string]$reportPath) {
    $p = $reportPath.Replace('\', '/')
    while ($p.StartsWith('./')) { $p = $p.Substring(2) }   # literal './', not a character set
    if ($tracked.Contains($p)) { return @{ Status = 'ok'; Count = 1 } }

    $matches = @()
    foreach ($t in $tracked) {
        $endsWith = {
            param($full, $tail)
            if ($full.Length -lt $tail.Length) { return $false }
            if (-not $full.EndsWith($tail, [System.StringComparison]::OrdinalIgnoreCase)) { return $false }
            return ($full.Length -eq $tail.Length) -or ($full[$full.Length - $tail.Length - 1] -eq '/')
        }
        if ((& $endsWith $t $p) -or (& $endsWith $p $t)) { $matches += $t }
    }
    if ($matches.Count -eq 1) { return @{ Status = 'ok'; Count = 1 } }
    if ($matches.Count -gt 1) { return @{ Status = 'ambiguous'; Count = $matches.Count } }
    return @{ Status = 'unmatched'; Count = 0 }
}

$checked = 0
$bad = @()

foreach ($report in (Get-ChildItem -Path $Path -Recurse -File -Include *.lcov, *.info, *.xml)) {
    foreach ($line in [System.IO.File]::ReadLines($report.FullName)) {
        $paths = @()
        if ($line -match '^\s*SF:(.+)$') { $paths += $Matches[1].Trim() }
        foreach ($m in [regex]::Matches($line, '<class[^>]*\bfilename="([^"]+)"')) { $paths += $m.Groups[1].Value }

        foreach ($p in $paths) {
            $checked++
            $r = Resolve-ReportPath $p
            if ($r.Status -eq 'unmatched') {
                $bad += "$($report.Name): $p  (no tracked file matches)"
            } elseif ($r.Status -eq 'ambiguous') {
                # Named distinctly: the server would store this file with Matched = false and drop it
                # from every number without an error, which looks identical to "we have no data".
                $bad += "$($report.Name): $p  (ambiguous - $($r.Count) tracked files match; the server requires exactly one)"
            }
        }
    }
}

if ($checked -eq 0) {
    Write-Error "no coverage report paths found under '$Path' — the reports are empty or missing"
    exit 2
}

if ($bad.Count -gt 0) {
    Write-Host "Coverage path tripwire FAILED — these paths would be silently dropped by the server:" -ForegroundColor Red
    $bad | Select-Object -Unique | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
    exit 1
}

Write-Host "Coverage path tripwire OK — $checked report path(s) resolve against git ls-files."
